pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: UseDotNet@2
  displayName: 'Install Core 5.0 SDK'
  inputs:
    packageType: 'sdk'
    version: '5.0.301'

- script: dotnet build -c Release
  displayName: 'dotnet build Release'

- script: dotnet test -c Debug
  displayName: 'dotnet test Debug'
